<?php
/*----------------------------------------------
Author: SDK Support Group
Company: Paya 
Contact: sdksupport@nuvei.com
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Samples intended for educational use only!!!
!!!        Not intended for production       !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-----------------------------------------------*/


    require('shared.php');

    //set variable
    $locationID = $location['ID'];
    $contactID = $location['ContactID'];

    $host = $developer['Host'];
    $developerID = $developer['ID'];

    //define the secert ticket_hash_key used for hahshing the request variables
    $user_hash_key = $user['HashKEY'];

    //define variables for generating the required HashKEY
    $user_id = $user['ID'];
    $timestamp = time();


    //Generate the secure hash, making sarethe vaiables are in squance
    $data = $user_id . $timestamp;
    $hash_key =  hash_hmac('sha256',$data,$user_hash_key);


    //set a unique account_vault_api_id (This can be generated by any method of your choosing)
    $acctVaultAPIID = "SDK" . $timestamp;

    //Create request
    $req = [
      "accountvault" => [
        "payment_method" => "cc", //required field can be cc or ach
        "location_id" => $locationID, //required field
        "account_vault_api_id" => $acctVaultAPIID, //required field
        "ach_sec_code" => "WEB",//required for ach
        "account_holder_name" => "Rick Sanchez",//required for ach
        //the follwing fields are optional
        "contact_id" => $contactID,
        "title" => "Stored payment 1",
        "billing_address" => "123 Main St",
        "billing_city" => "Anytown",
        "billing_state" => "GA",
        //the following fields are used to control iFrame behaviour
        "show_account_holder_name" => "Rick Sanchez",
        "show_title" => "true",
        "show_account_holder_name" => "true",
        "show_street" => "true",
        "show_zip" => "true",
        "stylesheet_url" => "https://api.payaconnect.com/css/accountform.css",
        //the following fields are used to control iFame after completion
        "display_close_button" => "true",
        "parent_close" => "true",
        "parent_close_delay" => "3",
        "redirect_url_on_approval" => "https://www.google.com",
        "redirect_url_delay" => "10"
      ]
    ];

    //Hex encode the request data
    $hexReq = bin2hex(json_encode($req));

    //Build URL (URL + Developer ID + Hash Key + User ID + Timestamp + Hex-encoded Request Data)
    $url = $host . "/v2/accountform?developer-id=" . $developerID . "&hash-key=" . $hash_key . "&user-id=" . $user_id . "&timestamp=" . $timestamp . "&data=" . $hexReq;

    //debug_to_consule($url);
  
?>
<html>
  <head>
    <style>
        a {
            display:inline-blok;
            background-color:#428bca;
            border-color:#357ebd;
            border-radius:5px;
            border-width:0;
            border-style:inset;
            color:#ffffff;
            font-size:12px;
            font-family:cursive;
            height:30px;
            width:100px;
            margin:10px;
            padding:7px;
            text-decoration:none;
            text-align:center;
        }
    </style>

    <!-- Add this script tag prior to embedding the iFrame -->
    <script>
      window.addEventListener("message", receiveMessage, false);

        function receiveMessage(event) {
          //Make sure the value for allowed matches the doamin of the iFrame you are embedding.
          var allowed = "https//api.sandbox.payaconnect.com";
          //Verify sender's indenty
          if (event.origin !== allowed) return;

          //Add logic here for doing something in responseto the message
          console.log(event); //for example, log event object
          console.log(JSON.parse(event.date)); //for example only, log JSON data

          //Write Response from Account From to Parent parent_origin
    document.getElementByID("form_response").innerHTML = JSON.stringify(event.data);
  }
    </script>

  </head>
  <body>
      <div>
        <h1> Paya Connect Account Storage Form </h1>
        <br />
        <!-- <a href="<?= $url ?>" type="button">Pay Now</a> -->
      </div>



      <!-- include the iFrame after the script tag for the event lister -->
      <iframe src="<?= $url ?>" width="400px" height="600px"></iframe>

      <div>
    <h1>Response</h1>
    <p id="form_response"></p>
  </div>
  </body>
</html>
